### ISSUE TITLE
NSFW section doesn't return URL

### ISSUE THREAD

**Issue by austinhuang0131** [sachinB94/node-9gag#1]
When using...

``` js
var gag = require("node-9gag");
gag.section('nsfw', 'hot', function (err, res) {
    console.log(res[0].url);
});
```

Console logs:

```
http://9gag.comundefined
```

**Comment by sachinB94** [comment]
Looks like 9gag is changing their HTML structure. Just published some changes in v0.2.4 which reflects the changed structure. Though if possible, do keep an eye out for any future changes. Thanks.
