### ISSUE TITLE
[IDEA] comments

### ISSUE THREAD

**Issue by RubenNL** [sachinB94/node-9gag#2]
Could you make it possible to view the comments?
Now i can only see the comment count.

**Comment by sachinB94** [comment]
This definitely can be done. But, loading comments is an entire different story than simple scraping. For 9gag, comments are a dynamic content, which will require something like `PhantomJs` to scrape. It will take time, which I current am unable to give. Though, I'd be happy to merge a pull request if anyone(you) is willing to do it. Thanks.

**Comment by RubenNL** [comment]
im working on it

**Comment by sachinB94** [comment]
Great.! I'll be waiting.

**Comment by RubenNL** [comment]
could you help me? this script gives the url of the json from the GAG'aGxd2nn'. 

var request = require('request');
var cheerio = require('cheerio');
var uri = 'http://9gag.com/gag/aGxd2nn';
String.prototype.replaceAll = function(search, replacement) {
    var target = this;
    return target.replace(new RegExp(search, 'g'), replacement);
};
request({
    uri: uri,
    method: 'GET'
}, function(err, res, html) {
    var $ = cheerio.load(html);
    $("script").each(function(index, value) {
        try {
            str = $(value).text();
            crop1 = str.substr(str.indexOf('=') + 2);
            crop2 = crop1.substr(0, crop1.indexOf(';'));
            crop3 = crop2.replaceAll("'", '"');
            array = JSON.parse(crop3);
            appid = array.appId;
            url = 'http://comment-cdn.9gag.com/v1/cacheable/comment-list.json?appId=' + appid + '&url=' + encodeURIComponent(uri) + '&count=10&level=2&order=score&mentionMapping=true&origin=9gag.com';
            console.log(url);
        } catch (e) {}
    });
});

in currently on mobile, and it is your project, but i think this must work.

**Comment by RubenNL** [comment]
i think it could be included in the getitem.js

**Comment by RubenNL** [comment]
var gag='<YOUR GAG ID>';
var length=10;
var request = require('request');
var cheerio = require('cheerio');
var uri = 'http://9gag.com/gag/'+gag;
String.prototype.replaceAll = function(search, replacement) {
    var target = this;
    return target.replace(new RegExp(search, 'g'), replacement);
};
request({
    uri: uri,
    method: 'GET'
}, function(err, res, html) {
    var $ = cheerio.load(html);
    $("script").each(function(index, value) {
        try {
            str = $(value).text();
            crop1 = str.substr(str.indexOf('=') + 2);
            crop2 = crop1.substr(0, crop1.indexOf(';'));
            crop3 = crop2.replaceAll("'", '"');
            array = JSON.parse(crop3);
            appid = array.appId;
            url = 'http://comment-cdn.9gag.com/v1/cacheable/comment-list.json?appId=' + appid + '&url=' + encodeURIComponent(uri) + '&count='+length+'&level=2&order=score&mentionMapping=true&origin=9gag.com';
            request({
                uri: url,
                method: 'GET'
            }, function(err, res, html) {
                $(JSON.parse(html).payload.comments).each(function(index, value) {
                    if (value.type == "text") {
                        console.log(value.user.displayName + ': ' + value.text);
                    }
                });
            });
        } catch (e) {}
    });
});

Github is not made for mobile:(

but, this gives the last 10(if you need more, edit the second line) comments of the gag with the id specified on the first line.

i have coded everything on mobile!

**Comment by RubenNL** [comment]
#6 I hope its good!

**Comment by RubenNL** [comment]
is reactions on comments also needed?

**Comment by RubenNL** [comment]
could you check my pull request? (#6)
